name: GiftCodeForMembers
author: ["CentOs"]
version: 0.0.1
description: This plugin for server !!!
main: CentOs\GiftCode
api: [2.0.0]
commands:
  gift:
    usage: /gift <item|vip|money> <code>
    description: "Gift code for your little members !!!"
permissions:
  gift.use:
    default: true
    description: "Player can using giftcode"
