name: GiftCodeForMembers
author: ["CentOs"]
version: 0.0.1
description: This plugin for server !!!
main: CentOs\GiftCode
api: [2.0.0]
commands:
  gift:
    usage: /gift <mems|vips> <code>
    description: "Gift code for your little members !!!"
permissions:
  gift.normal:
    default: op
    description: "Player can using giftcode"
  gift.vips:
    default: op
    description: "Player vips can using giftcode"
